# This document describes a ci-connect service.
# You can find more information about the ci-connect service definition here:
# https://github.wdf.sap.corp/ci-connect/ci-connect/blob/master/docs/customProcess/SharedService.md
---
id:                 "RefApps/SHINE"
displayName:        SHINE Integration Scenario
description:        This Service do a shine integration test scenario

webhook:            http://mo-b60444a56.mo.sap.corp:8080/ci-connect-webhook/
homepage:           https://mo-b60444a56.mo.sap.corp:8443
documentationUrl:   https://github.wdf.sap.corp/MyOrg/MyServiceDefinitionRepository/blob/branch/README.md

configRequired:     false

responsibles:       ['I056090']

accessKeys:         ['myKey']

publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAsEreKvZKJYXQNxn5+DWj
    mYObl0WfA4gjw6gtSWg/cUBtrS5DqGROK5VWnpQa7PnjDDfaTM+qLifztlRrlqJT
    3S/wq9KU+DB3WgwSz3chwzwJ6n/QDM0bHkWKh8fcLKCAqtcYux5i8hUTu69pqiLv
    lZmxMJXM5bJJfnJ8GOIIwQdyLW+sE771iztqqFp+GGT2M5o/eWm+YgN5T6HSQpSm
    yudGY8a0od4/H2L4s451jfadFu8NsD5H+eE4JAZkgrPv+/H04W13LbOadSbnBLmT
    faqIgwdhhIReyhlyMpfizjblN1/k/In5E5skJbE5Ip1WVn+577xRTT0EPbNcPjNx
    I2fV9120tNSe3YdoqH26FVjzgCkWyBIvhDOwFgOFFYPrJixCpEBo78QSYYaC7ml5
    Pd6sOnq0ptLAUM+kUm23Ct1ZCgWMRsVycKlgZd/ZLO+ytX6gyQSrYVuvFt5WmDqs
    A39Df6Ieuf1WwjChwG/o/kFeOWaq6MdTygKNvNqZ4yQZ1mXLp/BZIMoE/cMdDDF4
    gnUPPPRUiL48B4r8Ucp6Ljo3jPKC5wF9GU0ECLrNO5hssXuwwYrz3uhfkQ0tGS/h
    k7gtmKWuHjqVdmusYjPAWIjTKI4KsyfGScnWoY2U1SgnG7KLk6ltwo6gQvODXLLw
    d4/4SW/QC9cVtFpUxmTivJECASM=
    -----END PUBLIC KEY-----
