rules:
  - Branch: master
    attributes:
      deployUser: xsmaster
      deploySpace: initial
      deployApi: http://mo-ee79db595.mo.sap.corp:9999
      deployOrg: initial
      deployMethod: deploy
      deployMtaExtCsv: "config-op.mtaext"
      deployPassword: |
        Sd6j64nezP89ppQrObmToO89TrKv8oyGybw/Zcj6z/s8IOZGPV2YF+H4cMolHL+g
        slxNcKbaZfWrhkLSjQ/rHtTTPP07LI519Hy0YWaiscIhH6TaX/6/uw659uE9LWYe
        eAR5EknTvrJllTdvfpQn0CWhDCVbAlDWxrfWxg78IQMUQ1sKUMXPbm2CJmrTlvrd
        9DH6NW29r3ZVvu8jHKOpgGa5nBrybA2sN0rcD765dsicgg7yFRY3Tix1cTYbto/8
        vAq00q/20O9iWeaIakm6KTFpJD2SCGCoBcgxl0fY9WBzBYosLzhYQ8J9y8uyM9fK
        ckfwE/N2HuDuoSN0gFMzUg==