rules:
  - Branch: master
    attributes:
      deployUser: DEVX_TECH_USER
      deploySpace: PROD
      deployApi: https://mo-6fa335e64.mo.sap.corp:30030
      deployOrg: myorg
      deployMethod: deploy
      deployManifest: "manifest-test.yml"
      deployPassword: |
        UyySs293eyLkIysjXAm8BfKozZXvaHJFAEWUPZwFSCc2SoYCnWfGdNHMp7+Jqe1F
        CQQ4eHHhGfAQqEV4+qcoSZEvAaPSPmUwIE0QEw0LRcr1apEOQbhkAXknz8QLM+Pz
        dKSUyAryZfMuECO2Rbko3JnOyMp4tNUN8CM2ceR4XGqSL5N6LBERHHXEUlQthDN9
        un0Ksl/7Wi0hMefnGsGkaU8wZjCBeGZcP+cImxo+WgJ058l5/KwhpD/ai78vFlK2
        UCjXuHbQa3UHrlwObaBWHacFCR6dIawpQk4ApMPfP2aNPiDuOP2h3iEzWs1Vd4mG
        dP8sIiETFfN0NcU0PTLE/Q==
