rules:
  - Branch: master
    attributes:
      deployUser: DEVX_TECH_USER
      deploySpace: PROD
      deployApi: https://mo-33f723125.mo.sap.corp:30030
      deployOrg: myorg
      deployMethod: deploy
      deployManifest: "manifest-test.yml"
      deployPassword: |
        bmCTUAk01Y5Qut9rxYYt/0Hm7dizpsdAD9Y0KT41iAGm5k/vJOG3GUCm2q85+D5H
        xcaBhuFLwMwnSQYd5QZwOGGV/csAjkXU6PZBNPgAt/EdY4c3Wah4sb7CsaXyUmAO
        CPoKzNupxxIL4euI/+/1scTmE7RJfrFCWpnSnpk0VbxAhPdq9T0+It5c8W77c/0G
        Y64boZ4uOUVo1dZTSLBFEzQK2pvuSlHL+ekJhU2yLTWRMc6JueviNC0EHbf62I+s
        TGy9DsfY2wpIBUn3GZ7964rx4fjQwJ0R3sGIIvKk1CfeQprF2VfY5kaisOftyOOl
        jdadRHsZIqZm7Ym9zfiEGQ==


